version: "3"

services:

  app:
    env_file: ./.env
    build:
      context: .
    ports:
      - 0.0.0.0:8888:8888
    volumes:
      - gnames:/var/opt/gnames
    command:
      - rest
      - -p
      - "8888"
      - -d

volumes:
  gnames:

